version: "3.6"

services:
  postgres:
    build:
      context: ./postgres
    command: postgres -c 'temp_buffers=200MB' -c 'work_mem=200MB'
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  postgraphile:
    build:
      context: ./postgraphile
    command: >-
      --connection postgres://postgres:postgres@postgres:5432/postgres
      --schema public
      --watch
      --retry-on-init-fail
      --enable-query-batching
      --show-error-stack=json --extended-errors hint,detail,errcode
      --simple-collections only
      --no-setof-functions-contain-nulls
      --dynamic-json
      --append-plugins @graphile-contrib/pg-simplify-inflector,postgraphile-plugin-connection-filter
      --port 5000
      --graphql "/postgraphile/"
      --graphiql "/postgraphile/graphiql" --enhance-graphiql --allow-explain
    ports:
      - "5000:5000"

volumes:
  postgresdata:
