version: "3.6"

services:
  postgres:
    build:
      context: ./postgres
    command: postgres -c 'port=5001' -c 'temp_buffers=200MB' -c 'work_mem=200MB'
    environment:
      - PGPORT=5001
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5001:5001"
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./database_schema:/database_schema
      - ./scratch:/h5ad_store

  postgraphile:
    build:
      context: ./postgraphile
    environment:
      # study-level permissions are not in effect until permissions are set in the study table,
      # these are demo examples for testing:
      - AUTH_HEADER_NAME=x-amzn-oidc-accesstoken
      # - AUTH_HEADER_MOCK_VALUE=Group1;Group2
      - DATABASE_URL=postgres://postgraphile:postgraphile@postgres:5001/postgres
      # the postgraphile database user is sufficient for the API;
      # during development it is helpful to enable database schema watching in postgres,
      # which needs more permissions. (optional environment variable)
      - OWNER_DATABASE_URL=postgres://postgres:postgres@postgres:5001/postgres
      - PORT=5000
    ports:
      - "5000:5000"


  client:
    build:
      context: ./client
    ports:
      - "5002:5002"

volumes:
  postgresdata:
