.PHONY = download

IMPORT_STUDIES := $(wildcard scratch/bayer_studies/*.h5ad)
IMPORT_OK := $(IMPORT_STUDIES:.h5ad=.imported)

scratch/bayer_studies/%.imported: scratch/bayer_studies/%.h5ad
	PYTHONPATH=$$(pwd)/data_import python data_import/study_import.py $<
	echo "done" > $@

import_all: $(IMPORT_OK)

download:
	aws s3 sync s3://cellenium-prod/input_c2/ scratch/bayer_studies/

