name: cellenium_import
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pyjaspar
  # cello-classify needs pygraphviz, which requires the graphviz headers for compilation
  - graphviz
  - pip
  - pip:
    - pandas
    - numpy
    - scipy
    - requests
    - matplotlib
    - seaborn
    - scanpy
    - sqlalchemy
    - psycopg2-binary
    - jupyterlab
    - pybiomart
    - lxml
    - cello-classify
