name: cellenium_import
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pyjaspar
  # cello-classify needs pygraphviz, which requires the graphviz headers for compilation
  - graphviz
  - pip
  - pip:
    - -r study_import_requirements.txt
    - requests
    - matplotlib~=3.6.3
    - seaborn
    - jupyterlab
    - pybiomart
    - lxml
    - cello-classify
    - owlready2
    - pysam
    - mudatasets