name: cellenium_import
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip
  - pyjaspar
  - pip:
    - pandas
    - numpy
    - scipy
    - requests
    - matplotlib
    - seaborn
    - scanpy
    - sqlalchemy
    - psycopg2-binary
    - jupyterlab
    - 'dramatiq[watch]'
    - dramatiq-pg
    - pybiomart
    - lxml
