name: postgres_python
dependencies:
  - python=3.10
  - postgresql-plpython=15.1
  - scanpy
  - pandas
  - numpy
  - numba
  - scipy
  - requests
  - matplotlib
  - seaborn
  - networkx
  - pip
  - git
  - make
  - gcc
