name: postgres_python
dependencies:
  - python=3.10
  - postgresql-plpython=15.1
  - scanpy=1.9.*
  - muon
  - pandas=1.5.*
  - numpy=1.23.*
  - numba
  - scipy=1.10.*
  - requests
  - matplotlib=3.6.*
  - seaborn
  - networkx
  - python-jose
  - msal
  - boto3
  - smart_open
  - pip
  - git
  - make
  - gcc
